export const routes = {
    SIGNINSCREENS: 'SIGNINSCREENS',
    SIGNUPSCREENS: 'SIGNUPSCREENS',
    HOMESCREENS: 'HOMESCREENS',
    SEARCHSCREENS: 'SEARCHSCREENS',
    CONTENTSCREENS: 'CONTENTSCREENS',
    MARKETSCREENS: 'MARKETSCREENS',
    CONGRASCREENS: 'CONGRASCREENS',
    RATINGSCREENS: 'RATINGSCREENS',
    BLOGPOSTSCREENS: 'BLOGPOSTSCREENS',
    PROFILEPOSTSCREENS: 'PROFILEPOSTSCREENS',
    BOTTOMTABBAR: 'BOTTOMTABBAR',

  };